package dev.itmo.compiler.lexer;

public enum TokenType {

    FUNCTION, RETURN, IF, ELSE, WHILE, VAR, PRINT,

    INT, ARRAY,

    IDENTIFIER, NUMBER,

    PLUS, MINUS, MUL, DIV,
    ASSIGN,
    EQUALS, NOT_EQUALS, LESS_THAN, GREATER_THAN, LESS_EQUALS, GREATER_EQUALS,

    SEMICOLON, COMMA, DOT,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,

    EOF
}